import { useState, useEffect, useCallback } from 'react';

const cache: Record<string, Record<string, string>> = {};

async function fetchStrings(baseUrl: string, lang: string): Promise<Record<string, string>> {
  if (cache[lang]) return cache[lang];
  try {
    const res = await fetch(`${baseUrl}/api/config/languages/${lang}`);
    if (res.ok) {
      const data = await res.json();
      cache[lang] = data;
      return data;
    }
  } catch {}
  return {};
}

// Inline fallback strings (no server call needed for basic operation)
const FALLBACK: Record<string, Record<string, string>> = {
  es: {
    greeting: '¡Hola! ¿En qué puedo ayudarte?',
    placeholder: 'Escribe tu mensaje...',
    send: 'Enviar',
    escalate: 'Hablar con un agente',
    call: 'Llamar',
    offline_title: 'Fuera de horario',
    offline_message: 'Déjanos tus datos y te contactaremos.',
    offline_form_name: 'Nombre *',
    offline_form_email: 'Email *',
    offline_form_phone: 'Teléfono (opcional)',
    offline_form_message: 'Mensaje (opcional)',
    offline_form_submit: 'Enviar',
    welcome_title: 'Bienvenido a Redegal',
    welcome_subtitle: 'Estamos aquí para ayudarte.',
    typing: 'Escribiendo...',
    powered_by: 'Powered by Redegal',
    quick_reply_yes: 'Sí',
    quick_reply_no: 'No',
    quick_reply_more_info: 'Más información',
    quick_reply_contact: 'Contactar',
    quick_reply_pricing: 'Precios',
    back_to_chat: 'Volver al chat',
    end_conversation: 'Finalizar',
    csat_question: '¿Cómo valorarías tu experiencia?',
    csat_thanks: '¡Gracias!',
    rating_terrible: 'Pésima',
    rating_bad: 'Mala',
    rating_okay: 'Regular',
    rating_good: 'Buena',
    rating_excellent: 'Excelente',
    new_conversation: 'Nueva conversación',
    attach_file: 'Adjuntar',
    sound_on: 'Sonido activado',
    sound_off: 'Silenciar',
    connection_lost: 'Conexión perdida',
    reconnecting: 'Reconectando...',
    connected: 'Conectado',
    boostic: 'SEO & Growth',
    binnacle: 'Business Intelligence',
    marketing: 'Marketing Digital',
    tech: 'Desarrollo Tech',
    select_business_line: '¿Sobre qué servicio quieres saber más?',
    agent_connecting: 'Conectando con un agente...',
    no_agents: 'No hay agentes disponibles. ¿Puedo ayudarte?',
    file_upload: 'Subir archivo',
    file_too_large: 'Archivo demasiado grande (máx. 10 MB)',
    offline_form_thanks: '¡Recibido! Te contactaremos pronto.',
    lead_thanks: '¡Gracias, {{name}}! Te contactaremos pronto.',
    schedule_call: 'Programar llamada',
    rate_experience: 'Valora tu experiencia',
    help_center: 'Centro de ayuda',
    help_center_intro: 'Busca en nuestra base de conocimiento para encontrar respuestas rápidas.',
    ask_more: 'Preguntar más sobre esto',
    lead_form_title: 'Solicitar información',
    lead_form_subtitle: 'Déjanos tus datos y un experto se pondrá en contacto contigo.',
    // Call-related strings
    call_audio_quality: 'Calidad de audio',
    call_connection_poor: 'Conexión mala',
    call_connection_unstable: 'Conexión inestable',
    call_no_voice_detected: 'No detectamos tu voz. Comprueba el micrófono.',
    call_csat_thanks: 'Gracias por tu valoración',
    call_csat_question: '¿Cómo fue tu experiencia?',
    call_preflight_mic: 'Micrófono',
    call_preflight_connection: 'Conexión',
    call_preflight_server: 'Servidor',
    call_preflight_verifying: 'Verificando conexión...',
    call_calling: 'Llamando...',
    call_please_wait: 'Espere un momento',
    call_connecting: 'Conectando llamada...',
    call_will_receive: 'Recibirás una llamada en tu teléfono',
    call_establishing: 'Estableciendo conexión',
    call_queued: 'En cola',
    call_queue_position: 'Posición {{position}}',
    call_estimated_wait: 'Tiempo estimado: ~{{time}}',
    call_in_progress: 'Llamada en curso',
    call_unmute_mic: 'Activar micrófono',
    call_mute_mic: 'Silenciar micrófono',
    call_hangup: 'Colgar',
    call_on_hold: 'En espera...',
    call_agent_soon: 'El agente te atenderá en un momento',
    call_ended: 'Llamada finalizada',
    call_error: 'Error de conexión',
    call_retry: 'Reintentar',
    call_use_callback: 'Usar callback telefónico',
    call_we_call_you: 'Te llamamos',
    call_enter_phone: 'Introduce tu teléfono y te devolvemos la llamada en segundos',
    call_version_beta: 'Versión Beta',
    call_call_me_now: 'Llámadme ahora',
    call_back_to_chat: '← Volver al chat',
  },
  en: {
    greeting: 'Hello! How can I help you?',
    placeholder: 'Type your message...',
    send: 'Send',
    escalate: 'Talk to an agent',
    call: 'Call',
    offline_title: 'Outside business hours',
    offline_message: 'Leave your details and we will contact you.',
    offline_form_name: 'Name *',
    offline_form_email: 'Email *',
    offline_form_phone: 'Phone (optional)',
    offline_form_message: 'Message (optional)',
    offline_form_submit: 'Send',
    welcome_title: 'Welcome to Redegal',
    welcome_subtitle: 'We are here to help.',
    typing: 'Typing...',
    powered_by: 'Powered by Redegal',
    quick_reply_yes: 'Yes',
    quick_reply_no: 'No',
    quick_reply_more_info: 'More info',
    quick_reply_contact: 'Contact us',
    quick_reply_pricing: 'Pricing',
    back_to_chat: 'Back to chat',
    end_conversation: 'End chat',
    csat_question: 'How would you rate your experience?',
    csat_thanks: 'Thank you!',
    rating_terrible: 'Terrible',
    rating_bad: 'Bad',
    rating_okay: 'Okay',
    rating_good: 'Good',
    rating_excellent: 'Excellent',
    new_conversation: 'New conversation',
    attach_file: 'Attach',
    sound_on: 'Sound on',
    sound_off: 'Sound off',
    connection_lost: 'Connection lost',
    reconnecting: 'Reconnecting...',
    connected: 'Connected',
    boostic: 'SEO & Growth',
    binnacle: 'Business Intelligence',
    marketing: 'Digital Marketing',
    tech: 'Tech Development',
    select_business_line: 'Which service interests you?',
    agent_connecting: 'Connecting to an agent...',
    no_agents: 'No agents available. Can I help?',
    file_upload: 'Upload file',
    file_too_large: 'File too large (max 10 MB)',
    offline_form_thanks: 'Received! We will contact you soon.',
    lead_thanks: 'Thank you, {{name}}! We will contact you soon.',
    schedule_call: 'Schedule a call',
    rate_experience: 'Rate your experience',
    help_center: 'Help center',
    help_center_intro: 'Search our knowledge base for quick answers.',
    ask_more: 'Ask more about this',
    lead_form_title: 'Request information',
    lead_form_subtitle: 'Leave your details and an expert will contact you.',
    // Call-related strings
    call_audio_quality: 'Audio quality',
    call_connection_poor: 'Poor connection',
    call_connection_unstable: 'Unstable connection',
    call_no_voice_detected: 'We cannot detect your voice. Check your microphone.',
    call_csat_thanks: 'Thank you for your feedback',
    call_csat_question: 'How was your experience?',
    call_preflight_mic: 'Microphone',
    call_preflight_connection: 'Connection',
    call_preflight_server: 'Server',
    call_preflight_verifying: 'Verifying connection...',
    call_calling: 'Calling...',
    call_please_wait: 'Please wait',
    call_connecting: 'Connecting call...',
    call_will_receive: 'You will receive a call on your phone',
    call_establishing: 'Establishing connection',
    call_queued: 'In queue',
    call_queue_position: 'Position {{position}}',
    call_estimated_wait: 'Estimated wait: ~{{time}}',
    call_in_progress: 'Call in progress',
    call_unmute_mic: 'Unmute microphone',
    call_mute_mic: 'Mute microphone',
    call_hangup: 'Hang up',
    call_on_hold: 'On hold...',
    call_agent_soon: 'An agent will be with you shortly',
    call_ended: 'Call ended',
    call_error: 'Connection error',
    call_retry: 'Retry',
    call_use_callback: 'Use phone callback',
    call_we_call_you: 'We call you',
    call_enter_phone: 'Enter your phone number and we will call you back in seconds',
    call_version_beta: 'Beta Version',
    call_call_me_now: 'Call me now',
    call_back_to_chat: '← Back to chat',
  },
  pt: {
    greeting: 'Olá! Como posso ajudar?',
    placeholder: 'Escreva a sua mensagem...',
    send: 'Enviar',
    escalate: 'Falar com um agente',
    call: 'Ligar',
    offline_title: 'Fora do horário',
    offline_message: 'Deixe os seus dados e entraremos em contacto.',
    offline_form_name: 'Nome *',
    offline_form_email: 'Email *',
    offline_form_phone: 'Telefone (opcional)',
    offline_form_message: 'Mensagem (opcional)',
    offline_form_submit: 'Enviar',
    welcome_title: 'Bem-vindo à Redegal',
    welcome_subtitle: 'Estamos aqui para ajudar.',
    typing: 'A escrever...',
    powered_by: 'Powered by Redegal',
    quick_reply_yes: 'Sim',
    quick_reply_no: 'Não',
    quick_reply_more_info: 'Mais informação',
    quick_reply_contact: 'Contactar',
    quick_reply_pricing: 'Preços',
    back_to_chat: 'Voltar ao chat',
    end_conversation: 'Terminar',
    csat_question: 'Como avalia a sua experiência?',
    csat_thanks: 'Obrigado!',
    rating_terrible: 'Péssima',
    rating_bad: 'Má',
    rating_okay: 'Razoável',
    rating_good: 'Boa',
    rating_excellent: 'Excelente',
    new_conversation: 'Nova conversa',
    attach_file: 'Anexar',
    sound_on: 'Som ativado',
    sound_off: 'Silenciar',
    connection_lost: 'Conexão perdida',
    reconnecting: 'A reconectar...',
    connected: 'Conectado',
    boostic: 'SEO & Growth',
    binnacle: 'Business Intelligence',
    marketing: 'Marketing Digital',
    tech: 'Desenvolvimento Tech',
    select_business_line: 'Que serviço lhe interessa?',
    agent_connecting: 'A conectar com um agente...',
    no_agents: 'Nenhum agente disponível. Posso ajudar?',
    file_upload: 'Carregar ficheiro',
    file_too_large: 'Ficheiro demasiado grande (máx. 10 MB)',
    offline_form_thanks: 'Recebido! Entraremos em contacto em breve.',
    lead_thanks: 'Obrigado, {{name}}! Entraremos em contacto em breve.',
    schedule_call: 'Agendar chamada',
    rate_experience: 'Avalie a sua experiência',
    help_center: 'Centro de ajuda',
    help_center_intro: 'Pesquise na nossa base de conhecimento para encontrar respostas rápidas.',
    ask_more: 'Perguntar mais sobre isto',
    lead_form_title: 'Solicitar informação',
    lead_form_subtitle: 'Deixe os seus dados e um especialista entrará em contacto.',
    // Call-related strings
    call_audio_quality: 'Qualidade de áudio',
    call_connection_poor: 'Conexão fraca',
    call_connection_unstable: 'Conexão instável',
    call_no_voice_detected: 'Não detetámos a sua voz. Verifique o microfone.',
    call_csat_thanks: 'Obrigado pela sua avaliação',
    call_csat_question: 'Como foi a sua experiência?',
    call_preflight_mic: 'Microfone',
    call_preflight_connection: 'Conexão',
    call_preflight_server: 'Servidor',
    call_preflight_verifying: 'A verificar conexão...',
    call_calling: 'A ligar...',
    call_please_wait: 'Aguarde um momento',
    call_connecting: 'A conectar chamada...',
    call_will_receive: 'Receberá uma chamada no seu telefone',
    call_establishing: 'A estabelecer conexão',
    call_queued: 'Em fila',
    call_queue_position: 'Posição {{position}}',
    call_estimated_wait: 'Tempo estimado: ~{{time}}',
    call_in_progress: 'Chamada em curso',
    call_unmute_mic: 'Ativar microfone',
    call_mute_mic: 'Silenciar microfone',
    call_hangup: 'Desligar',
    call_on_hold: 'Em espera...',
    call_agent_soon: 'Um agente atenderá em breve',
    call_ended: 'Chamada terminada',
    call_error: 'Erro de conexão',
    call_retry: 'Tentar novamente',
    call_use_callback: 'Usar callback telefónico',
    call_we_call_you: 'Nós ligamos',
    call_enter_phone: 'Introduza o seu telefone e devolvemos a chamada em segundos',
    call_version_beta: 'Versão Beta',
    call_call_me_now: 'Liguem-me agora',
    call_back_to_chat: '← Voltar ao chat',
  },
  gl: {
    greeting: 'Ola! En que podo axudarte?',
    placeholder: 'Escribe a túa mensaxe...',
    send: 'Enviar',
    escalate: 'Falar cun axente',
    call: 'Chamar',
    offline_title: 'Fóra de horario',
    offline_message: 'Déixanos os teus datos e contactaremos contigo.',
    offline_form_name: 'Nome *',
    offline_form_email: 'Email *',
    offline_form_phone: 'Teléfono (opcional)',
    offline_form_message: 'Mensaxe (opcional)',
    offline_form_submit: 'Enviar',
    welcome_title: 'Benvido a Redegal',
    welcome_subtitle: 'Estamos aquí para axudarte.',
    typing: 'Escribindo...',
    powered_by: 'Powered by Redegal',
    quick_reply_yes: 'Si',
    quick_reply_no: 'Non',
    quick_reply_more_info: 'Máis información',
    quick_reply_contact: 'Contactar',
    quick_reply_pricing: 'Prezos',
    back_to_chat: 'Volver ao chat',
    end_conversation: 'Finalizar',
    csat_question: 'Como valorarías a túa experiencia?',
    csat_thanks: 'Grazas!',
    rating_terrible: 'Pésima',
    rating_bad: 'Mala',
    rating_okay: 'Regular',
    rating_good: 'Boa',
    rating_excellent: 'Excelente',
    new_conversation: 'Nova conversa',
    attach_file: 'Adxuntar',
    sound_on: 'Son activado',
    sound_off: 'Silenciar',
    connection_lost: 'Conexión perdida',
    reconnecting: 'Reconectando...',
    connected: 'Conectado',
    boostic: 'SEO & Growth',
    binnacle: 'Business Intelligence',
    marketing: 'Marketing Dixital',
    tech: 'Desenvolvemento Tech',
    select_business_line: 'Sobre que servizo queres saber máis?',
    agent_connecting: 'Conectando cun axente...',
    no_agents: 'Non hai axentes dispoñibles. Podo axudarte?',
    file_upload: 'Subir arquivo',
    file_too_large: 'Arquivo demasiado grande (máx. 10 MB)',
    offline_form_thanks: 'Recibido! Contactaremos contigo pronto.',
    lead_thanks: 'Grazas, {{name}}! Contactaremos contigo pronto.',
    schedule_call: 'Programar chamada',
    rate_experience: 'Valora a túa experiencia',
    help_center: 'Centro de axuda',
    help_center_intro: 'Busca na nosa base de coñecemento para atopar respostas rápidas.',
    ask_more: 'Preguntar máis sobre isto',
    lead_form_title: 'Solicitar información',
    lead_form_subtitle: 'Déixanos os teus datos e un experto contactará contigo.',
    // Call-related strings
    call_audio_quality: 'Calidade de audio',
    call_connection_poor: 'Conexión mala',
    call_connection_unstable: 'Conexión inestable',
    call_no_voice_detected: 'Non detectamos a túa voz. Comproba o micrófono.',
    call_csat_thanks: 'Grazas pola túa valoración',
    call_csat_question: 'Como foi a túa experiencia?',
    call_preflight_mic: 'Micrófono',
    call_preflight_connection: 'Conexión',
    call_preflight_server: 'Servidor',
    call_preflight_verifying: 'Verificando conexión...',
    call_calling: 'Chamando...',
    call_please_wait: 'Agarda un momento',
    call_connecting: 'Conectando chamada...',
    call_will_receive: 'Recibirás unha chamada no teu teléfono',
    call_establishing: 'Establecendo conexión',
    call_queued: 'En cola',
    call_queue_position: 'Posición {{position}}',
    call_estimated_wait: 'Tempo estimado: ~{{time}}',
    call_in_progress: 'Chamada en curso',
    call_unmute_mic: 'Activar micrófono',
    call_mute_mic: 'Silenciar micrófono',
    call_hangup: 'Colgar',
    call_on_hold: 'En espera...',
    call_agent_soon: 'O axente atenderache nun momento',
    call_ended: 'Chamada finalizada',
    call_error: 'Erro de conexión',
    call_retry: 'Reintentar',
    call_use_callback: 'Usar callback telefónico',
    call_we_call_you: 'Chamámoste',
    call_enter_phone: 'Introduce o teu teléfono e devolvémosche a chamada en segundos',
    call_version_beta: 'Versión Beta',
    call_call_me_now: 'Chamádeme agora',
    call_back_to_chat: '← Volver ao chat',
  },
};

export function useLanguage(lang: string, baseUrl?: string) {
  const [strings, setStrings] = useState<Record<string, string>>(FALLBACK[lang] || FALLBACK['es']);

  useEffect(() => {
    if (baseUrl) {
      fetchStrings(baseUrl, lang).then((s) => {
        if (Object.keys(s).length > 0) setStrings(s);
        else setStrings(FALLBACK[lang] || FALLBACK['es']);
      });
    } else {
      setStrings(FALLBACK[lang] || FALLBACK['es']);
    }
  }, [lang, baseUrl]);

  const t = useCallback((key: string, vars: Record<string, string> = {}): string => {
    let str = strings[key] || FALLBACK['es']?.[key] || key;
    for (const [k, v] of Object.entries(vars)) {
      str = str.replace(new RegExp(`\\{\\{${k}\\}\\}`, 'g'), v);
    }
    return str;
  }, [strings]);

  return { t, isRTL: false };
}
