const STRINGS: Record<string, Record<string, string>> = {
  es: {
    greeting: '¡Hola! Soy el asistente virtual de Redegal. ¿En qué puedo ayudarte?',
    placeholder: 'Escribe tu mensaje...',
    send: 'Enviar',
    boostic: 'SEO y Growth',
    binnacle: 'Business Intelligence',
    marketing: 'Marketing Digital',
    tech: 'Desarrollo Tech',
    select_line: '¿Sobre qué servicio te gustaría saber más?',
    escalate: 'Hablar con un agente',
    call: 'Llamar',
    offline_title: 'Fuera de horario',
    offline_message: 'Déjanos tus datos y te contactaremos.',
    name: 'Nombre *',
    email: 'Email *',
    phone: 'Teléfono (opcional)',
    message: 'Mensaje (opcional)',
    submit: 'Enviar',
    thanks: '¡Gracias! Te contactaremos pronto.',
    powered: 'Redegal',
    csat_question: '¿Cómo valorarías tu experiencia?',
  },
  gl: {
    greeting: 'Ola! Son o asistente virtual de Redegal. En que podo axudarche?',
    placeholder: 'Escribe a túa mensaxe...',
    send: 'Enviar',
    boostic: 'SEO e Growth',
    binnacle: 'Business Intelligence',
    marketing: 'Marketing Dixital',
    tech: 'Desenvolvemento Tech',
    select_line: 'Sobre que servizo che gustaría saber máis?',
    escalate: 'Falar cun axente',
    call: 'Chamar',
    offline_title: 'Fóra de horario',
    offline_message: 'Déixanos os teus datos e contactarémoste.',
    name: 'Nome *',
    email: 'Email *',
    phone: 'Teléfono (opcional)',
    message: 'Mensaxe (opcional)',
    submit: 'Enviar',
    thanks: 'Grazas! Contactarémoste axiña.',
    powered: 'Redegal',
    csat_question: 'Como valorarías a túa experiencia?',
  },
  en: {
    greeting: "Hello! I'm Redegal's virtual assistant. How can I help you?",
    placeholder: 'Type your message...',
    send: 'Send',
    boostic: 'SEO & Growth',
    binnacle: 'Business Intelligence',
    marketing: 'Digital Marketing',
    tech: 'Tech Development',
    select_line: 'Which service would you like to know more about?',
    escalate: 'Talk to an agent',
    call: 'Call',
    offline_title: 'Outside business hours',
    offline_message: 'Leave your details and we will contact you.',
    name: 'Name *',
    email: 'Email *',
    phone: 'Phone (optional)',
    message: 'Message (optional)',
    submit: 'Send',
    thanks: 'Thank you! We will contact you soon.',
    powered: 'Redegal',
    csat_question: 'How would you rate your experience?',
  },
  'es-MX': {
    greeting: '¡Hola! Soy el asistente virtual de Redegal. ¿En qué te puedo ayudar?',
    placeholder: 'Escribe tu mensaje...',
    send: 'Enviar',
    boostic: 'SEO y Growth',
    binnacle: 'Business Intelligence',
    marketing: 'Marketing Digital',
    tech: 'Desarrollo Tech',
    select_line: '¿Sobre qué servicio te gustaría saber más?',
    escalate: 'Hablar con un agente',
    call: 'Llamar',
    offline_title: 'Fuera de horario',
    offline_message: 'Déjanos tus datos y te contactaremos.',
    name: 'Nombre *',
    email: 'Correo electrónico *',
    phone: 'Teléfono (opcional)',
    message: 'Mensaje (opcional)',
    submit: 'Enviar',
    thanks: '¡Gracias! Te contactaremos pronto.',
    powered: 'Redegal',
    csat_question: '¿Cómo calificarías tu experiencia?',
  },
};

export function useLanguage(lang: string) {
  const t = (key: string): string => {
    return STRINGS[lang]?.[key] || STRINGS['es']?.[key] || key;
  };
  return { t };
}
